services:
  - type: web
    name: nexus-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SECRET_KEY
        value: 'django-insecure-k+g7%o4xu-9n*=5guqgb$8%nwfqyb*41%n1nu(i!3es2c#sx%9'
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: nexus-backend-bye3.onrender.com,localhost,127.0.0.1
      - key: CORS_ALLOWED_ORIGINS
        value: https://nexus-frontend-eta.vercel.app,http://localhost:5713
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "True"

